version: '3.7'
services:
  postgres:
    container_name: yolo_postgres
    networks:
      - yolo
    image: postgres:13.2-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - postgres:/var/lib/postgresql/data
  flask:
    deploy:
      resources:
        limits:
          memory: 20g
        reservations:
          memory: 20g
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
      # remove tty to not keep it alive
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # keep true to see prints in console when running without -d
    tty: true
    # yolo memory problem
    # Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
    ipc: host
    networks:
      - yolo
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    build:
      context:
        .
    container_name: yolo_flask
  calculation:
    networks:
      - yolo
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: "eee:latest"
    ports:
      - "8000:8000"

networks:
  yolo:

volumes:
  postgres:
